### ISSUE TITLE
Invalid database environment

### ISSUE THREAD

**Issue by dtolj** [santana/activerecord-informix-adapter#2]
I have configured unixODBC to work with Informix by following this document: http://www.unixodbc.org/doc/informix.html

I am trying to query an existing Informix database using RoR.

My Interpreter:
Ruby 1.9.2

My installed gems:
gem 'rails', '3.2.3'
gem 'ruby-informix'
gem 'activerecord-informix-adapter'
gem 'dbd-odbc'
gem 'ruby-odbc'
gem 'activerecord-odbc-adapter'

Inside database.yml configuration file, I made a new entry.

```
custom_db: 
    adapter: informix
    mode: odbc
    dsn: miecr
    username: name
    password: secret
```

I made a new Model.

```
class Person < ActiveRecord::Base
  establish_connection 'custom_db'
  self.table_name = 'Person'
end
```

When I test the web application I get this error:
Informix::DatabaseError (Invalid database environment.):

Does activerecord-informix-adapter work with ODBC?
