### ISSUE TITLE
undefined method `primary_key'

### ISSUE THREAD

**Issue by dtolj** [santana/activerecord-informix-adapter#3]
I have added a new entry in my database.yml

```
ciscortd: 
  adapter: informix
  database: mydatabase@myserver
  username: user
  password: secret
```

The error I am getting is: NoMethodError 
undefined method `primary_key' for #ActiveRecord::ConnectionAdapters::InformixAdapter:0xac47cc8

My table is very simple and it has a Primary key:

```
    profileid int NOT NULL,
    autowork smallint NOT NULL,
    wrapuptime smallint NOT NULL,
    PRIMARY KEY (profileid)
```

Using Ruby 1.9.2
Rails 3.2.3
